apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.AppName }}-exporter-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.AppName }}-exporter
  namespaceSelector:
    matchNames:
      - koden-clients
  endpoints:
  - port: 9117
    path: /metrics
    interval: 15s