apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.AppName }}-exporter-monitor
  namespace: {{ .Values.NameSpace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.AppName }}-exporter
  endpoints:
  - port: metrics
    interval: 15s