apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-exporter-service
  namespace: {{ .Values.NameSpace }}
spec:
  ports:
  - port: 9117
    targetPort: 9117
  selector:
    app: {{ .Values.AppName }}-exporter
  type: ClusterIP