apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.AppName }}-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.AppName }}
  namespaceSelector:
    matchNames:
      - koden-clients
  endpoints:
  - port: "9117"
    path: /metrics
    interval: 15s
