apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}-exporter
  namespace: {{ .Values.NameSpace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.AppName }}-exporter
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}-exporter
    spec:
      containers:
      - name: apache-exporter
        image: lusotycoon/apache-exporter:v1.0.9
        args:
          - "-s=http://{{ .Values.AppName }}-service:80/server-status?auto"
        ports:
        - containerPort: 9117